name: "Podcast Generator"
author: "Aashik"
description: "Generates a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: "The email Address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The name"
    required: true
    default: ${{ github.actor }}